<?php

use Illuminate\Database\Seeder;

class CountyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('counties')->insert([
           ['id' => '1','county' => 'CARONI'],
            ['id' => '2','county' => 'MAYARO'],
            ['id' => '3','county' => 'NARIVA'],
            ['id' => '4','county' => 'ST. ANDREW'],
            ['id' => '5','county' => 'ST. DAVID'],
            ['id' => '6','county' => 'ST. GEORGE'],
            ['id' => '7','county' => 'ST. PATRICK'],
            ['id' => '8','county' => 'TOBAGO'],
            ['id' => '9','county' => 'VICTORIA'],
        ]);

        DB::table('wards')->insert([
            ['id' => '1','ward' => 'ARIMA','county_id' => '6'],
            ['id' => '2','ward' => 'BLANCHISSEUSE','county_id' => '6'],
            ['id' => '3','ward' => 'CEDROS','county_id' => '7'],
            ['id' => '4','ward' => 'CHAGUANAS','county_id' => '1'],
            ['id' => '5','ward' => 'CHARUMA','county_id' => '3'],
            ['id' => '6','ward' => 'COCAL','county_id' => '3'],
            ['id' => '7','ward' => 'COUVA','county_id' => '1'],
            ['id' => '8','ward' => 'CUNUPIA','county_id' => '1'],
            ['id' => '9','ward' => 'DIEGO MARTIN','county_id' => '6'],
            ['id' => '10','ward' => 'ERIN','county_id' => '7'],
            ['id' => '11','ward' => 'GUAYAGUAYARE','county_id' => '2'],
            ['id' => '12','ward' => 'LA BREA','county_id' => '7'],
            ['id' => '13','ward' => 'MANZANILLA','county_id' => '4'],
            ['id' => '14','ward' => 'MATURA','county_id' => '4'],
            ['id' => '15','ward' => 'MAYARO','county_id' => '2'],
            ['id' => '16','ward' => 'MONTSERRAT','county_id' => '1'],
            ['id' => '17','ward' => 'MORUGA','county_id' => '9'],
            ['id' => '18','ward' => 'NAPARIMA','county_id' => '9'],
            ['id' => '19','ward' => 'ORTOIRE','county_id' => '9'],
            ['id' => '20','ward' => 'POINTE-A-PIERRE','county_id' => '9'],
            ['id' => '21','ward' => 'PORT OF SPAIN (CITY)','county_id' => '6'],
            ['id' => '22','ward' => 'SAN FERNANDO','county_id' => '9'],
            ['id' => '23','ward' => 'SAN RAPHAEL','county_id' => '6'],
            ['id' => '24','ward' => 'SAVANNA GRANDE','county_id' => '9'],
            ['id' => '25','ward' => 'SIPARIA','county_id' => '7'],
            ['id' => '26','ward' => 'ST. ANDREW','county_id' => '8'],
            ['id' => '27','ward' => 'ST. ANNS','county_id' => '6'],
            ['id' => '28','ward' => 'ST. DAVID','county_id' => '8'],
            ['id' => '29','ward' => 'ST. GEORGE','county_id' => '8'],
            ['id' => '30','ward' => 'ST. JOHN','county_id' => '8'],
            ['id' => '31','ward' => 'ST. MARY','county_id' => '8'],
            ['id' => '32','ward' => 'ST. PATRICK','county_id' => '8'],
            ['id' => '33','ward' => 'ST. PAUL','county_id' => '8'],
            ['id' => '34','ward' => 'TACARIGUA','county_id' => '6'],
            ['id' => '35','ward' => 'TAMANA','county_id' => '4'],
            ['id' => '36','ward' => 'TOCO','county_id' => '5'],
            ['id' => '37','ward' => 'TURURE','county_id' => '4'],
            ['id' => '38','ward' => 'VALENCIA','county_id' => '4'],
        ]);

        DB::table('districts')->insert([
            ['id' => '1','district' => 'ABYSINIA VILLAGE (OILFIELD AREA)','ward_id' => '11'],
            ['id' => '2','district' => 'ACONO VILLAGE','ward_id' => '34'],
            ['id' => '3','district' => 'AGOSTINI VILLAGE','ward_id' => '4'],
            ['id' => '4','district' => 'ALYCE GLEN','ward_id' => '9'],
            ['id' => '5','district' => 'ANGLAIS SETTLEMENT','ward_id' => '36'],
            ['id' => '6','district' => 'APEX OIL FIELD','ward_id' => '25'],
            ['id' => '7','district' => 'ARANGUEZ','ward_id' => '27'],
            ['id' => '8','district' => 'ARENA','ward_id' => '4'],
            ['id' => '9','district' => 'ARENA VILLAGE','ward_id' => '10'],
            ['id' => '10','district' => 'ARGYLE/KENDAL','ward_id' => '33'],
            ['id' => '11','district' => 'ARIMA','ward_id' => '1'],
            ['id' => '12','district' => 'ARIMA HEIGHTS/TEMPLE VILLAGE','ward_id' => '1'],
            ['id' => '13','district' => 'ARIMA PROPER','ward_id' => '1'],
            ['id' => '14','district' => 'ARIPERO VILLAGE','ward_id' => '12'],
            ['id' => '15','district' => 'ARNOS VALE','ward_id' => '30'],
            ['id' => '16','district' => 'AROUCA','ward_id' => '34'],
            ['id' => '17','district' => 'AUDALUSIA','ward_id' => '1'],
            ['id' => '18','district' => 'AVOCAT VILLAGE','ward_id' => '25'],
            ['id' => '19','district' => 'BACOLET','ward_id' => '26'],
            ['id' => '20','district' => 'BAGATELLE','ward_id' => '9'],
            ['id' => '21','district' => 'BALANDRA','ward_id' => '14'],
            ['id' => '22','district' => 'BALMAIN','ward_id' => '7'],
            ['id' => '23','district' => 'BAMBOO GROVE(ST. ANNS)','ward_id' => '27'],
            ['id' => '24','district' => 'BAMBOO GROVE(TACARIGUA)','ward_id' => '34'],
            ['id' => '25','district' => 'BAMBOO VILLAGE','ward_id' => '3'],
            ['id' => '26','district' => 'BANK VILLAGE','ward_id' => '4'],
            ['id' => '27','district' => 'BARATARIA','ward_id' => '27'],
            ['id' => '28','district' => 'BARRACKPORE','ward_id' => '18'],
            ['id' => '29','district' => 'BASSE TERRE(CHAGUANAS)','ward_id' => '4'],
            ['id' => '30','district' => 'BASSE TERRE(COCAL)','ward_id' => '6'],
            ['id' => '31','district' => 'BASSE TERRE(MORUGA)','ward_id' => '17'],
            ['id' => '32','district' => 'BASTA HALL','ward_id' => '7'],
            ['id' => '33','district' => 'BASTER HALL','ward_id' => '7'],
            ['id' => '34','district' => 'BATCHYIA VILLAGE','ward_id' => '25'],
            ['id' => '35','district' => 'BAYSHORE','ward_id' => '9'],
            ['id' => '36','district' => 'BEACH CAMP','ward_id' => '25'],
            ['id' => '37','district' => 'BEETHAM ESTATE','ward_id' => '27'],
            ['id' => '38','district' => 'BEJUCAL(CHAGUNAS)','ward_id' => '4'],
            ['id' => '39','district' => 'BEJUCAL(CUNUPIA)','ward_id' => '8'],
            ['id' => '40','district' => 'BELLE GARDENS','ward_id' => '33'],
            ['id' => '41','district' => 'BELMONT(PORT OF SPAIN)','ward_id' => '21'],
            ['id' => '42','district' => 'BELMONT(ST. ANNS)','ward_id' => '27'],
            ['id' => '43','district' => 'BEN LOMOND(SAN FERNANDO)','ward_id' => '22'],
            ['id' => '44','district' => 'BEN LOMOND(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '45','district' => 'BENNET VILLAGE','ward_id' => '10'],
            ['id' => '46','district' => 'BETHEL','ward_id' => '32'],
            ['id' => '47','district' => 'BETHEL/MT.GOMERY','ward_id' => '32'],
            ['id' => '48','district' => 'BICHE','ward_id' => '37'],
            ['id' => '49','district' => 'BIG YARD','ward_id' => '9'],
            ['id' => '50','district' => 'BLACK ROCK','ward_id' => '32'],
            ['id' => '51','district' => 'BLANCHISSEUSE','ward_id' => '2'],
            ['id' => '52','district' => 'BLANCHISSEUSE VILLAGE','ward_id' => '2'],
            ['id' => '53','district' => 'BLOODY BAY','ward_id' => '30'],
            ['id' => '54','district' => 'BLUE BASIN','ward_id' => '9'],
            ['id' => '55','district' => 'BLUE RANGE','ward_id' => '9'],
            ['id' => '56','district' => 'BOIS JEAN JEAN','ward_id' => '17'],
            ['id' => '57','district' => 'BOISSIERE','ward_id' => '9'],
            ['id' => '58','district' => 'BON ACCORD','ward_id' => '32'],
            ['id' => '59','district' => 'BON AIR DEVELOPMENT','ward_id' => '34'],
            ['id' => '60','district' => 'BON AIR WEST DEVELOPMENT','ward_id' => '34'],
            ['id' => '61','district' => 'BON JEAN','ward_id' => '17'],
            ['id' => '62','district' => 'BONASSE VILLAGE','ward_id' => '3'],
            ['id' => '63','district' => 'BONNE AVENTURE(ORTOIRE)','ward_id' => '19'],
            ['id' => '64','district' => 'BONNE AVENTURE(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '65','district' => 'BORDE NARVE(NAPARIMA)','ward_id' => '18'],
            ['id' => '66','district' => 'BORDE NARVE(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '67','district' => 'BRASSO CAPARO VILLAGE (Chaguanas)','ward_id' => '4'],
            ['id' => '68','district' => 'BRASSO CAPARO VILLAGE (Monsterrat)','ward_id' => '16'],
            ['id' => '69','district' => 'BRASSO MANUEL JUNCTION','ward_id' => '16'],
            ['id' => '70','district' => 'BRASSO SECO VILLAGE(ARIMA)','ward_id' => '1'],
            ['id' => '71','district' => 'BRASSO SECO VILLAGE(BLANCHISSEUSE)','ward_id' => '2'],
            ['id' => '72','district' => 'BRASSO TAMANA','ward_id' => '16'],
            ['id' => '73','district' => 'BRASSO VENADO(COUVA)','ward_id' => '7'],
            ['id' => '74','district' => 'BRASSO VENADO(MONTSERRAT)','ward_id' => '16'],
            ['id' => '75','district' => 'BRASSO WARD','ward_id' => '16'],
            ['id' => '76','district' => 'BRECHIN CASTLE','ward_id' => '7'],
            ['id' => '77','district' => 'BRICKFIELD','ward_id' => '4'],
            ['id' => '78','district' => 'BRICKFIELD/NAVET','ward_id' => '35'],
            ['id' => '79','district' => 'BRIGHTON','ward_id' => '12'],
            ['id' => '80','district' => 'BRISTOL VILLAGE(COCAL)','ward_id' => '6'],
            ['id' => '81','district' => 'BRISTOL VILLAGE(MAYARO)','ward_id' => '15'],
            ['id' => '82','district' => 'BROADWAY','ward_id' => '22'],
            ['id' => '83','district' => 'BRONTE VILLAGE','ward_id' => '18'],
            ['id' => '84','district' => 'BROOKLYN SETTLEMENT','ward_id' => '13'],
            ['id' => '85','district' => 'BROOMAGE','ward_id' => '24'],
            ['id' => '86','district' => 'BROTHERS ROAD','ward_id' => '16'],
            ['id' => '87','district' => 'BROTHERS SETTLEMENT','ward_id' => '24'],
            ['id' => '88','district' => 'BUCCOO/CORAL GARDENS','ward_id' => '32'],
            ['id' => '89','district' => 'BUEN INTENTO','ward_id' => '24'],
            ['id' => '90','district' => 'BUTLER VILLAGE','ward_id' => '4'],
            ['id' => '91','district' => 'CAIGUAL','ward_id' => '13'],
            ['id' => '92','district' => 'CALCUTTA ROAD NO.2','ward_id' => '16'],
            ['id' => '93','district' => 'CALCUTTA SETTLEMENT NO.2','ward_id' => '7'],
            ['id' => '94','district' => 'CALDER HALL/FRIENDSFIELD','ward_id' => '26'],
            ['id' => '95','district' => 'CALIFORNIA','ward_id' => '7'],
            ['id' => '96','district' => 'CALVARY HILL','ward_id' => '1'],
            ['id' => '97','district' => 'CAMERON ROAD','ward_id' => '9'],
            ['id' => '98','district' => 'CANAAN','ward_id' => '32'],
            ['id' => '99','district' => 'CANAAN VILLAGE/PALMISTE','ward_id' => '18'],
            ['id' => '100','district' => 'CANE FARM','ward_id' => '34'],
            ['id' => '101','district' => 'CANQUE','ward_id' => '5'],
            ['id' => '102','district' => 'CANTARO VILLAGE','ward_id' => '27'],
            ['id' => '103','district' => 'CAP DE VILLE','ward_id' => '12'],
            ['id' => '104','district' => 'CAPARO','ward_id' => '4'],
            ['id' => '105','district' => 'CAPILDEO BLOCK','ward_id' => '7'],
            ['id' => '106','district' => 'CARAPICHAIMA (CHAGUANAS)','ward_id' => '4'],
            ['id' => '107','district' => 'CARAPICHAIMA (COUVA)','ward_id' => '7'],
            ['id' => '108','district' => 'CARAPO','ward_id' => '1'],
            ['id' => '109','district' => 'CARATAL','ward_id' => '20'],
            ['id' => '110','district' => 'CARENAGE','ward_id' => '9'],
            ['id' => '111','district' => 'CARIB HOMES','ward_id' => '1'],
            ['id' => '112','district' => 'CARLSEN FIELD','ward_id' => '4'],
            ['id' => '113','district' => 'CARONI VILLAGE(CHAGUANAS)','ward_id' => '4'],
            ['id' => '114','district' => 'CARONI VILLAGE(TACARIGUA)','ward_id' => '34'],
            ['id' => '115','district' => 'CASCADE','ward_id' => '27'],
            ['id' => '116','district' => 'CASTARA','ward_id' => '28'],
            ['id' => '117','district' => 'CAURA','ward_id' => '34'],
            ['id' => '118','district' => 'CEDAR HILL ESTATE','ward_id' => '13'],
            ['id' => '119','district' => 'CEDAR HILL(NAPARIMA)','ward_id' => '18'],
            ['id' => '120','district' => 'CEDAR HILL(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '121','district' => 'CEDROS','ward_id' => '3'],
            ['id' => '122','district' => 'CENTENO','ward_id' => '34'],
            ['id' => '123','district' => 'CHAGUANAS PROPER','ward_id' => '4'],
            ['id' => '124','district' => 'CHAGUARAMAS','ward_id' => '9'],
            ['id' => '125','district' => 'CHAMP ELYSEES','ward_id' => '9'],
            ['id' => '126','district' => 'CHAMP FLEURS(ST. ANNS)','ward_id' => '27'],
            ['id' => '127','district' => 'CHAMP FLEURS(TACARIGUA)','ward_id' => '34'],
            ['id' => '128','district' => 'CHANDERNAGORE','ward_id' => '4'],
            ['id' => '129','district' => 'CHARLIEVILLE','ward_id' => '4'],
            ['id' => '130','district' => 'CHARLOTTEVILLE','ward_id' => '30'],
            ['id' => '131','district' => 'CHARUMA VILLAGE','ward_id' => '5'],
            ['id' => '132','district' => 'CHASE VILLAGE','ward_id' => '4'],
            ['id' => '133','district' => 'CHATHAM','ward_id' => '3'],
            ['id' => '134','district' => 'CHICKLAND','ward_id' => '16'],
            ['id' => '135','district' => 'CHIN CHIN','ward_id' => '8'],
            ['id' => '136','district' => 'CHINESE VILLAGE','ward_id' => '12'],
            ['id' => '137','district' => 'CHURKOO VILLAGE','ward_id' => '18'],
            ['id' => '138','district' => 'CINNAMON HALL(GOV&#39;T HOUSE)','ward_id' => '26'],
            ['id' => '139','district' => 'CITY PROPER(NAPARIMA)','ward_id' => '18'],
            ['id' => '140','district' => 'CITY PROPER(SAN FERNANDO)','ward_id' => '22'],
            ['id' => '141','district' => 'CITY PROPER(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '142','district' => 'CLAXTON BAY','ward_id' => '7'],
            ['id' => '143','district' => 'CLEAVER ROAD','ward_id' => '1'],
            ['id' => '144','district' => 'CLEGHORN AND MT. PLEASANT','ward_id' => '7'],
            ['id' => '145','district' => 'COAL HILL','ward_id' => '13'],
            ['id' => '146','district' => 'COALMINE','ward_id' => '37'],
            ['id' => '147','district' => 'COCAL ESTATE/MAYARO','ward_id' => '6'],
            ['id' => '148','district' => 'COCHRANE','ward_id' => '12'],
            ['id' => '149','district' => 'COCORITE','ward_id' => '9'],
            ['id' => '150','district' => 'COCOYEA VILLAGE','ward_id' => '18'],
            ['id' => '151','district' => 'CONCORDIA','ward_id' => '29'],
            ['id' => '152','district' => 'CORINTH','ward_id' => '18'],
            ['id' => '153','district' => 'COROMANDEL','ward_id' => '3'],
            ['id' => '154','district' => 'COROSAL','ward_id' => '20'],
            ['id' => '155','district' => 'CORYAL VILLAGE','ward_id' => '24'],
            ['id' => '156','district' => 'CORYAL(MANZANILLA)','ward_id' => '13'],
            ['id' => '157','district' => 'CORYAL(TAMANA)','ward_id' => '35'],
            ['id' => '158','district' => 'COUVA CENTRAL','ward_id' => '7'],
            ['id' => '159','district' => 'COUVA(COUVA)','ward_id' => '7'],
            ['id' => '160','district' => 'COUVA(MONTSERRAT)','ward_id' => '16'],
            ['id' => '161','district' => 'COVIGNE','ward_id' => '9'],
            ['id' => '162','district' => 'CROWN POINT','ward_id' => '32'],
            ['id' => '163','district' => 'CUMACA','ward_id' => '38'],
            ['id' => '164','district' => 'CUMANA','ward_id' => '36'],
            ['id' => '165','district' => 'CUMUTO(ARIMA)','ward_id' => '1'],
            ['id' => '166','district' => 'CUMUTO(TAMANA)','ward_id' => '35'],
            ['id' => '167','district' => 'CUNARIPO','ward_id' => '35'],
            ['id' => '168','district' => 'CUNUPIA(CHAGUANAS)','ward_id' => '4'],
            ['id' => '169','district' => 'CUNUPIA(CUNUPIA)','ward_id' => '8'],
            ['id' => '170','district' => 'CUREPE','ward_id' => '34'],
            ['id' => '171','district' => 'CUSHE VILLAGE','ward_id' => '5'],
            ['id' => '172','district' => 'D&#39;ABADIE','ward_id' => '1'],
            ['id' => '173','district' => 'DARREL SPRING','ward_id' => '26'],
            ['id' => '174','district' => 'DE GANNES VILLAGE','ward_id' => '25'],
            ['id' => '175','district' => 'DEBE PROPER','ward_id' => '18'],
            ['id' => '176','district' => 'DEEP RAVINE/CLEAR WATER','ward_id' => '6'],
            ['id' => '177','district' => 'DEHLI SETTLEMENT','ward_id' => '25'],
            ['id' => '178','district' => 'DELAFORD(ST. PATRICK)','ward_id' => '32'],
            ['id' => '179','district' => 'DELAFORD(ST. PAUL)','ward_id' => '33'],
            ['id' => '180','district' => 'DIAMOND','ward_id' => '18'],
            ['id' => '181','district' => 'DIAMOND VALE','ward_id' => '9'],
            ['id' => '182','district' => 'DIBE/BELLE VUE','ward_id' => '9'],
            ['id' => '183','district' => 'DIEGO MARTIN PROPER','ward_id' => '9'],
            ['id' => '184','district' => 'DINSLEY','ward_id' => '34'],
            ['id' => '185','district' => 'DINSLEY/TRINCITY (SUNRISE PK)','ward_id' => '34'],
            ['id' => '186','district' => 'DOW VILLAGE(COUVA)','ward_id' => '7'],
            ['id' => '187','district' => 'DOW VILLAGE(SIPARIA)','ward_id' => '25'],
            ['id' => '188','district' => 'DUNCAN VILLAGE','ward_id' => '18'],
            ['id' => '189','district' => 'DURANTA GARDENS','ward_id' => '13'],
            ['id' => '190','district' => 'DYERS VILLAGE','ward_id' => '24'],
            ['id' => '191','district' => 'EAST PORT OF SPAIN','ward_id' => '21'],
            ['id' => '192','district' => 'EASTERN QUARRY','ward_id' => '27'],
            ['id' => '193','district' => 'ECCLES VILLAGE','ward_id' => '24'],
            ['id' => '194','district' => 'ECCLESVILLE','ward_id' => '6'],
            ['id' => '195','district' => 'EDINBURGH 500','ward_id' => '4'],
            ['id' => '196','district' => 'EDINBURGH GARDENS','ward_id' => '4'],
            ['id' => '197','district' => 'EDINBURGH VILLAGE','ward_id' => '4'],
            ['id' => '198','district' => 'EGYPT VILLAGE','ward_id' => '12'],
            ['id' => '199','district' => 'EL DORADO','ward_id' => '34'],
            ['id' => '200','district' => 'EL SOCORRO','ward_id' => '27'],
            ['id' => '201','district' => 'EL SOCORRO EXTENSION','ward_id' => '27'],
            ['id' => '202','district' => 'ELLERSLIE PARK','ward_id' => '21'],
            ['id' => '203','district' => 'EMBACADRE','ward_id' => '18'],
            ['id' => '204','district' => 'EMERALD GARDENS','ward_id' => '1'],
            ['id' => '205','district' => 'ENDEAVOUR VILLAGE','ward_id' => '4'],
            ['id' => '206','district' => 'ENTERPRISE','ward_id' => '4'],
            ['id' => '207','district' => 'ERIN PROPER','ward_id' => '10'],
            ['id' => '208','district' => 'ERIN/BUENOS AYRES','ward_id' => '10'],
            ['id' => '209','district' => 'ESMERALDA','ward_id' => '8'],
            ['id' => '210','district' => 'ESPERANCE VILLAGE','ward_id' => '18'],
            ['id' => '211','district' => 'ESPERANZA','ward_id' => '7'],
            ['id' => '212','district' => 'FAIRVIEW','ward_id' => '16'],
            ['id' => '213','district' => 'FANNY VILLAGE','ward_id' => '12'],
            ['id' => '214','district' => 'FARNUM VILLAGE','ward_id' => '20'],
            ['id' => '215','district' => 'FEBEAU VILLAGE','ward_id' => '27'],
            ['id' => '216','district' => 'FEDERATION PARK','ward_id' => '21'],
            ['id' => '217','district' => 'FELICITY','ward_id' => '4'],
            ['id' => '218','district' => 'FELICITY HALL','ward_id' => '7'],
            ['id' => '219','district' => 'FIFTH COMPANY','ward_id' => '19'],
            ['id' => '220','district' => 'FISHING POND','ward_id' => '14'],
            ['id' => '221','district' => 'FIVE RIVERS','ward_id' => '34'],
            ['id' => '222','district' => 'FLANAGIN TOWN(CHAGUANAS)','ward_id' => '4'],
            ['id' => '223','district' => 'FLANAGIN TOWN(MONSERRAT)','ward_id' => '16'],
            ['id' => '224','district' => 'FONROSE VILLAGE','ward_id' => '5'],
            ['id' => '225','district' => 'FOREST RESERVE','ward_id' => '12'],
            ['id' => '226','district' => 'FORRES PARK(COUVA)','ward_id' => '7'],
            ['id' => '227','district' => 'FORRES PARK(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '228','district' => 'FORT GEORGE','ward_id' => '9'],
            ['id' => '229','district' => 'FOUR ROADS - TAMANA','ward_id' => '37'],
            ['id' => '230','district' => 'FOUR ROADS(DIEGO MARTIN)','ward_id' => '9'],
            ['id' => '231','district' => 'FREDERICK SETTLEMENT','ward_id' => '8'],
            ['id' => '232','district' => 'FREEPORT(CHAGUANAS)','ward_id' => '4'],
            ['id' => '233','district' => 'FREEPORT(MONTSERRAT)','ward_id' => '16'],
            ['id' => '234','district' => 'FRIENDSHIP','ward_id' => '18'],
            ['id' => '235','district' => 'FYZABAD','ward_id' => '25'],
            ['id' => '236','district' => 'GASPARILLO','ward_id' => '20'],
            ['id' => '237','district' => 'GEORGE VILLAGE','ward_id' => '19'],
            ['id' => '238','district' => 'GLAMORGAN','ward_id' => '31'],
            ['id' => '239','district' => 'GLENCOE','ward_id' => '9'],
            ['id' => '240','district' => 'GOLCONDA(COUVA)','ward_id' => '7'],
            ['id' => '241','district' => 'GOLCONDA(NAPARIMA)','ward_id' => '18'],
            ['id' => '242','district' => 'GOLDEN LANE','ward_id' => '28'],
            ['id' => '243','district' => 'GOLDSBOROUGH','ward_id' => '31'],
            ['id' => '244','district' => 'GONZALES','ward_id' => '21'],
            ['id' => '245','district' => 'GONZALES (POINT FORTIN)','ward_id' => '12'],
            ['id' => '246','district' => 'GOODWOOD','ward_id' => '31'],
            ['id' => '247','district' => 'GOODWOOD GARDENS','ward_id' => '9'],
            ['id' => '248','district' => 'GRAN COUVA','ward_id' => '16'],
            ['id' => '249','district' => 'GRAN CURUCAYE','ward_id' => '27'],
            ['id' => '250','district' => 'GRAND LAGOON','ward_id' => '11'],
            ['id' => '251','district' => 'GRAND RIVIERE','ward_id' => '36'],
            ['id' => '252','district' => 'GRANVILLE','ward_id' => '3'],
            ['id' => '253','district' => 'GREEN ACRES','ward_id' => '22'],
            ['id' => '254','district' => 'GREEN HILL VILLAGE','ward_id' => '9'],
            ['id' => '255','district' => 'GUAICO','ward_id' => '35'],
            ['id' => '256','district' => 'GUAPO','ward_id' => '12'],
            ['id' => '257','district' => 'GUAPO LOT 10','ward_id' => '12'],
            ['id' => '258','district' => 'GUARACARA(NAPARIMA)','ward_id' => '17'],
            ['id' => '259','district' => 'GUARACARA(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '260','district' => 'GUATOPAJARO','ward_id' => '35'],
            ['id' => '261','district' => 'GUAYAGUAYARE','ward_id' => '11'],
            ['id' => '262','district' => 'GULF VIEW','ward_id' => '18'],
            ['id' => '263','district' => 'HARMONY HALL','ward_id' => '24'],
            ['id' => '264','district' => 'HARRIS VILLAGE','ward_id' => '25'],
            ['id' => '265','district' => 'HEIGHTS OF ARIPO','ward_id' => '1'],
            ['id' => '266','district' => 'HEIGHTS OF GUANAPO','ward_id' => '1'],
            ['id' => '267','district' => 'HERMITAGE (TOBAGO)','ward_id' => '30'],
            ['id' => '268','district' => 'HERMITAGE VILLAGE','ward_id' => '18'],
            ['id' => '269','district' => 'HERMITAGE(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '270','district' => 'HOLLYWOOD','ward_id' => '12'],
            ['id' => '271','district' => 'HOMELAND GARDENS','ward_id' => '4'],
            ['id' => '272','district' => 'HOPE FARM/JOHN DIAL','ward_id' => '29'],
            ['id' => '273','district' => 'HOPE/BHENHEIM','ward_id' => '29'],
            ['id' => '274','district' => 'HOWSEN VILLAGE','ward_id' => '35'],
            ['id' => '275','district' => 'ICACOS','ward_id' => '3'],
            ['id' => '276','district' => 'IERE VILLAGE (Naparima)','ward_id' => '18'],
            ['id' => '277','district' => 'IERE VILLAGE (Savanna Grande)','ward_id' => '24'],
            ['id' => '278','district' => 'INDIAN TRAIL','ward_id' => '7'],
            ['id' => '279','district' => 'INDIAN WALK','ward_id' => '19'],
            ['id' => '280','district' => 'INDUSTRIAL ESTATE','ward_id' => '9'],
            ['id' => '281','district' => 'JACOB SETTLEMENT','ward_id' => '25'],
            ['id' => '282','district' => 'JERNINGHAM JUNCTION(CUNUPIA)','ward_id' => '8'],
            ['id' => '283','district' => 'JERNINGHAM JUNCTION(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '284','district' => 'JORDAN VILLAGE','ward_id' => '18'],
            ['id' => '285','district' => 'KANDAHAR','ward_id' => '34'],
            ['id' => '286','district' => 'KELLY VILLAGE','ward_id' => '8'],
            ['id' => '287','district' => 'KING&#39;S BAY','ward_id' => '33'],
            ['id' => '288','district' => 'KING&#39;S WHARF','ward_id' => '22'],
            ['id' => '289','district' => 'KRONSTADT ISLAND','ward_id' => '9'],
            ['id' => '290','district' => 'KUMAR VILLAGE','ward_id' => '24'],
            ['id' => '291','district' => 'LA BREA','ward_id' => '12'],
            ['id' => '292','district' => 'LA CANOA','ward_id' => '27'],
            ['id' => '293','district' => 'LA FORTUNE','ward_id' => '18'],
            ['id' => '294','district' => 'LA FORTUNE/PLUCK','ward_id' => '25'],
            ['id' => '295','district' => 'LA HORQUETTA','ward_id' => '1'],
            ['id' => '296','district' => 'LA HORQUETTE','ward_id' => '9'],
            ['id' => '297','district' => 'LA LAJA','ward_id' => '1'],
            ['id' => '298','district' => 'LA LUNE','ward_id' => '17'],
            ['id' => '299','district' => 'LA MANGO VILLAGE','ward_id' => '34'],
            ['id' => '300','district' => 'LA PAILLE VILLAGE','ward_id' => '34'],
            ['id' => '301','district' => 'LA PASTORA','ward_id' => '27'],
            ['id' => '302','district' => 'LA PUERTA','ward_id' => '9'],
            ['id' => '303','district' => 'LA RESOURCE','ward_id' => '1'],
            ['id' => '304','district' => 'LA ROMAIN','ward_id' => '18'],
            ['id' => '305','district' => 'LA RUFFIN','ward_id' => '17'],
            ['id' => '306','district' => 'LA SAVANNE','ward_id' => '17'],
            ['id' => '307','district' => 'LA SEIVA','ward_id' => '9'],
            ['id' => '308','district' => 'LA SEIVA VILLAGE(MANZANILLA)','ward_id' => '13'],
            ['id' => '309','district' => 'LA SEIVA VILLAGE(TACARIGUA)','ward_id' => '34'],
            ['id' => '310','district' => 'LADY CHANCELLOR','ward_id' => '27'],
            ['id' => '311','district' => 'LAMBEAU','ward_id' => '26'],
            ['id' => '312','district' => 'LANGE PARK','ward_id' => '4'],
            ['id' => '313','district' => 'L&#39;ANSE FOURMI','ward_id' => '30'],
            ['id' => '314','district' => 'LANSE MITAN','ward_id' => '9'],
            ['id' => '315','district' => 'LANSE NOIR','ward_id' => '36'],
            ['id' => '316','district' => 'LAS CUEVAS','ward_id' => '2'],
            ['id' => '317','district' => 'LAS LOMAS (NOS. 1 & 2)','ward_id' => '8'],
            ['id' => '318','district' => 'LAVENTILLE','ward_id' => '27'],
            ['id' => '319','district' => 'LENDORE VILLAGE','ward_id' => '4'],
            ['id' => '320','district' => 'LENGUA VILLAGE','ward_id' => '24'],
            ['id' => '321','district' => 'LENGUA VILLAGE/BARRACKPORE','ward_id' => '18'],
            ['id' => '322','district' => 'LES EFFORTS EAST','ward_id' => '18'],
            ['id' => '323','district' => 'LES EFFORTS WEST','ward_id' => '18'],
            ['id' => '324','district' => 'LIBERTVILLE','ward_id' => '5'],
            ['id' => '325','district' => 'LONG CIRCULAR','ward_id' => '21'],
            ['id' => '326','district' => 'LONGDENVILLE','ward_id' => '4'],
            ['id' => '327','district' => 'LOPINOT VILLAGE','ward_id' => '34'],
            ['id' => '328','district' => 'LOS BAJOS','ward_id' => '10'],
            ['id' => '329','district' => 'LOS IROS/ERIN','ward_id' => '10'],
            ['id' => '330','district' => 'LOTHIAN','ward_id' => '24'],
            ['id' => '331','district' => 'LOUIS D&#39;OR','ward_id' => '33'],
            ['id' => '332','district' => 'LOWER HILL SIDE','ward_id' => '22'],
            ['id' => '333','district' => 'LOWER SANTA CRUZ','ward_id' => '27'],
            ['id' => '334','district' => 'LURE','ward_id' => '31'],
            ['id' => '335','district' => 'MACAULAY','ward_id' => '7'],
            ['id' => '336','district' => 'MACOYA','ward_id' => '34'],
            ['id' => '337','district' => 'MADRAS SETTLEMENT','ward_id' => '8'],
            ['id' => '338','district' => 'MAFEKING(COCAL)','ward_id' => '6'],
            ['id' => '339','district' => 'MAFEKING(ORTOIRE)','ward_id' => '19'],
            ['id' => '340','district' => 'MAINGOTVILLE','ward_id' => '7'],
            ['id' => '341','district' => 'MALABAR','ward_id' => '1'],
            ['id' => '342','district' => 'MALGRETOUTE','ward_id' => '24'],
            ['id' => '343','district' => 'MALICK','ward_id' => '27'],
            ['id' => '344','district' => 'MALONEY GARDENS','ward_id' => '34'],
            ['id' => '345','district' => 'MAMORAL NO.2(CHAGUNAS)','ward_id' => '4'],
            ['id' => '346','district' => 'MAMORAL NO.2(MONSERRAT)','ward_id' => '16'],
            ['id' => '347','district' => 'MANZANILLA','ward_id' => '13'],
            ['id' => '348','district' => 'MARABELLA(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '349','district' => 'MARABELLA(SAN FERNANDO)','ward_id' => '22'],
            ['id' => '350','district' => 'MARACAS','ward_id' => '27'],
            ['id' => '351','district' => 'MARACAS BAY','ward_id' => '27'],
            ['id' => '352','district' => 'MARACAS/ST. JOSEPH','ward_id' => '34'],
            ['id' => '353','district' => 'MARAJ HILL','ward_id' => '37'],
            ['id' => '354','district' => 'MARAJ LANDS','ward_id' => '22'],
            ['id' => '355','district' => 'MARAVAL PROPER','ward_id' => '9'],
            ['id' => '356','district' => 'MARIE ROAD','ward_id' => '27'],
            ['id' => '357','district' => 'MASON HALL','ward_id' => '29'],
            ['id' => '358','district' => 'MATELOT','ward_id' => '36'],
            ['id' => '359','district' => 'MATILDA','ward_id' => '24'],
            ['id' => '360','district' => 'MATURA','ward_id' => '14'],
            ['id' => '361','district' => 'MATURITA','ward_id' => '1'],
            ['id' => '362','district' => 'MAUSICA','ward_id' => '1'],
            ['id' => '363','district' => 'MAYARO(GUAYAGUAYARE)','ward_id' => '11'],
            ['id' => '364','district' => 'MAYARO(MAYARO)','ward_id' => '15'],
            ['id' => '365','district' => 'MAYO(MONTSERRAT)','ward_id' => '16'],
            ['id' => '366','district' => 'MAYO(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '367','district' => 'Mc BEAN','ward_id' => '7'],
            ['id' => '368','district' => 'MELAJO','ward_id' => '38'],
            ['id' => '369','district' => 'MENDEZ VILLAGE','ward_id' => '25'],
            ['id' => '370','district' => 'MESOPOTAMIA','ward_id' => '29'],
            ['id' => '371','district' => 'MILFORD COURT/PIGEON POINT','ward_id' => '32'],
            ['id' => '372','district' => 'MOKA','ward_id' => '9'],
            ['id' => '373','district' => 'MON DESIR','ward_id' => '12'],
            ['id' => '374','district' => 'MON REPOS (Morvant)','ward_id' => '29'],
            ['id' => '375','district' => 'MON REPOS (S&#39;do)','ward_id' => '18'],
            ['id' => '376','district' => 'MONKEY TOWN','ward_id' => '18'],
            ['id' => '377','district' => 'MONTE VIDEO','ward_id' => '36'],
            ['id' => '378','district' => 'MONTROSE VILLAGE(CHAGUANAS)','ward_id' => '4'],
            ['id' => '379','district' => 'MONTROSE VILLAGE(COUVA)','ward_id' => '7'],
            ['id' => '380','district' => 'MORA SETTLEMENT','ward_id' => '6'],
            ['id' => '381','district' => 'MORIAH','ward_id' => '28'],
            ['id' => '382','district' => 'MORIN BAY','ward_id' => '13'],
            ['id' => '383','district' => 'MORNE DIABLO','ward_id' => '25'],
            ['id' => '384','district' => 'MORNE L&#39; ENFER','ward_id' => '12'],
            ['id' => '385','district' => 'MORUGA','ward_id' => '17'],
            ['id' => '386','district' => 'MORUGA VILLAGE(MORUGA)','ward_id' => '17'],
            ['id' => '387','district' => 'MORUGA VILLAGE(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '388','district' => 'MORVANT','ward_id' => '27'],
            ['id' => '389','district' => 'MOUNT D&#39;OR','ward_id' => '27'],
            ['id' => '390','district' => 'MOUNT GRACE','ward_id' => '29'],
            ['id' => '391','district' => 'MOUNT MARIE','ward_id' => '26'],
            ['id' => '392','district' => 'MOUNT PLEASANT','ward_id' => '1'],
            ['id' => '393','district' => 'MOUNT ST. BENEDICT','ward_id' => '34'],
            ['id' => '394','district' => 'MOUNT ST. GEORGE(ST. GEORGE)','ward_id' => '29'],
            ['id' => '395','district' => 'MOUNT ST. GEORGE(ST. MARY)','ward_id' => '31'],
            ['id' => '396','district' => 'MT. HOPE','ward_id' => '27'],
            ['id' => '397','district' => 'MT. IRVINE/BLACK ROCK','ward_id' => '32'],
            ['id' => '398','district' => 'MT. LAMBERT','ward_id' => '27'],
            ['id' => '399','district' => 'MT. PLEASANT','ward_id' => '32'],
            ['id' => '400','district' => 'MUCURAPO','ward_id' => '9'],
            ['id' => '401','district' => 'MUNDO NUEVO(ARIMA)','ward_id' => '1'],
            ['id' => '402','district' => 'MUNDO NUEVO(SAN RAPHAEL)','ward_id' => '23'],
            ['id' => '403','district' => 'MUNDO NUEVO(ST. ANNS)','ward_id' => '27'],
            ['id' => '404','district' => 'MUNROE SETTLEMENT','ward_id' => '8'],
            ['id' => '405','district' => 'NANCOO VILLAGE','ward_id' => '8'],
            ['id' => '406','district' => 'NAVET VILLAGE','ward_id' => '6'],
            ['id' => '407','district' => 'NEVER DIRTY','ward_id' => '27'],
            ['id' => '408','district' => 'NEW GRANT(ORTOIRE)','ward_id' => '19'],
            ['id' => '409','district' => 'NEW GRANT(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '410','district' => 'NEW VILLAGE','ward_id' => '12'],
            ['id' => '411','district' => 'NEWLANDS','ward_id' => '12'],
            ['id' => '412','district' => 'NEWTOWN','ward_id' => '21'],
            ['id' => '413','district' => 'NORTH MANZANILLA','ward_id' => '13'],
            ['id' => '414','district' => 'NORTH POST','ward_id' => '9'],
            ['id' => '415','district' => 'OLD RANGE/SOU SOU LANDS','ward_id' => '32'],
            ['id' => '416','district' => 'OLTON ROAD','ward_id' => '1'],
            ['id' => '417','district' => 'O&#39;MEARA ROAD','ward_id' => '1'],
            ['id' => '418','district' => 'ORANGE GROVE ESTATE','ward_id' => '34'],
            ['id' => '419','district' => 'ORANGE GROVE(ARIMA)','ward_id' => '1'],
            ['id' => '420','district' => 'ORANGE GROVE(TACARIGUA)','ward_id' => '34'],
            ['id' => '421','district' => 'ORANGE VALLEY','ward_id' => '4'],
            ['id' => '422','district' => 'OROPOUCHE','ward_id' => '13'],
            ['id' => '423','district' => 'OROPUNA VILLAGE/PIARCO','ward_id' => '34'],
            ['id' => '424','district' => 'ORTOIRE(ORTOIRE)','ward_id' => '19'],
            ['id' => '425','district' => 'ORTOIRE(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '426','district' => 'OUPLAY VILLAGE','ward_id' => '7'],
            ['id' => '427','district' => 'PALMISTE','ward_id' => '18'],
            ['id' => '428','district' => 'PALMYRA','ward_id' => '18'],
            ['id' => '429','district' => 'PALMYRA VILLAGE/MT. STEWART','ward_id' => '18'],
            ['id' => '430','district' => 'PALO SECO','ward_id' => '10'],
            ['id' => '431','district' => 'PARADISE EAST','ward_id' => '34'],
            ['id' => '432','district' => 'PARAMIN','ward_id' => '9'],
            ['id' => '433','district' => 'PARFORCE','ward_id' => '20'],
            ['id' => '434','district' => 'PARLATUVIER','ward_id' => '30'],
            ['id' => '435','district' => 'PARRY LANDS SOUTH','ward_id' => '12'],
            ['id' => '436','district' => 'PASEA EXTENSION','ward_id' => '34'],
            ['id' => '437','district' => 'PATIENCE HILL','ward_id' => '32'],
            ['id' => '438','district' => 'PATNA VILLAGE','ward_id' => '9'],
            ['id' => '439','district' => 'PEMBROKE','ward_id' => '31'],
            ['id' => '440','district' => 'PENAL ROCK ROAD','ward_id' => '25'],
            ['id' => '441','district' => 'PENAL(NAPARIMA)','ward_id' => '18'],
            ['id' => '442','district' => 'PENAL(SIPARIA)','ward_id' => '25'],
            ['id' => '443','district' => 'PEPPER VILLAGE(COUVA)','ward_id' => '7'],
            ['id' => '444','district' => 'PEPPER VILLAGE(MONTSERRAT)','ward_id' => '16'],
            ['id' => '445','district' => 'PETERSFIELD','ward_id' => '4'],
            ['id' => '446','district' => 'PETIT BOURG','ward_id' => '27'],
            ['id' => '447','district' => 'PETIT CURUCAYE','ward_id' => '27'],
            ['id' => '448','district' => 'PETIT MORNE','ward_id' => '18'],
            ['id' => '449','district' => 'PETIT VALLEY','ward_id' => '9'],
            ['id' => '450','district' => 'PEYTONVILLE','ward_id' => '1'],
            ['id' => '451','district' => 'PHILIPINES(NAPARIMA)','ward_id' => '18'],
            ['id' => '452','district' => 'PHILIPINES(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '453','district' => 'PHOENIX PARK','ward_id' => '7'],
            ['id' => '454','district' => 'PICTON(NAPARIMA)','ward_id' => '18'],
            ['id' => '455','district' => 'PICTON(ST. ANNS)','ward_id' => '27'],
            ['id' => '456','district' => 'PINTO ROAD','ward_id' => '1'],
            ['id' => '457','district' => 'PIPARO','ward_id' => '20'],
            ['id' => '458','district' => 'PLAISANCE','ward_id' => '11'],
            ['id' => '459','district' => 'PLAISANCE PARK','ward_id' => '20'],
            ['id' => '460','district' => 'PLEASANTVILLE','ward_id' => '18'],
            ['id' => '461','district' => 'PLUM MITAN','ward_id' => '37'],
            ['id' => '462','district' => 'PLYMOUTH','ward_id' => '28'],
            ['id' => '463','district' => 'POINT CUMANA','ward_id' => '9'],
            ['id' => '464','district' => 'POINT D&#39;OR','ward_id' => '12'],
            ['id' => '465','district' => 'POINT FORTIN PROPER','ward_id' => '12'],
            ['id' => '466','district' => 'POINT FORTIN(CEDROS)','ward_id' => '3'],
            ['id' => '467','district' => 'POINT FORTIN(LA BREA)','ward_id' => '12'],
            ['id' => '468','district' => 'POINT FORTIN(SIPARIA)','ward_id' => '25'],
            ['id' => '469','district' => 'POINT LIGOURE','ward_id' => '12'],
            ['id' => '470','district' => 'POINT LISAS (INDUSTRIAL ESTATE)','ward_id' => '7'],
            ['id' => '471','district' => 'POINT LISAS (NHA)','ward_id' => '7'],
            ['id' => '472','district' => 'POOLE','ward_id' => '5'],
            ['id' => '473','district' => 'POONAH','ward_id' => '24'],
            ['id' => '474','district' => 'PORT OF SPAIN','ward_id' => '21'],
            ['id' => '475','district' => 'PORT OF SPAIN PORT AREA','ward_id' => '21'],
            ['id' => '476','district' => 'PREYSAL','ward_id' => '16'],
            ['id' => '477','district' => 'PRINCES TOWN PROPER(COUVA)','ward_id' => '7'],
            ['id' => '478','district' => 'PRINCES TOWN PROPER(SAN FERNANDO)','ward_id' => '22'],
            ['id' => '479','district' => 'PRINCES TOWN PROPER(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '480','district' => 'PRINCES TOWN(NAPARIMA)','ward_id' => '18'],
            ['id' => '481','district' => 'PRINCES TOWN(SAVANNA GRANDE0','ward_id' => '24'],
            ['id' => '482','district' => 'QUARRY VILLAGE','ward_id' => '25'],
            ['id' => '483','district' => 'RADIX','ward_id' => '11'],
            ['id' => '484','district' => 'RAMBERT VILLAGE','ward_id' => '18'],
            ['id' => '485','district' => 'RAMPANALGAS','ward_id' => '14'],
            ['id' => '486','district' => 'RANCHO QUEMADO','ward_id' => '10'],
            ['id' => '487','district' => 'RAVINE SABLE','ward_id' => '4'],
            ['id' => '488','district' => 'REAL SPRINGS','ward_id' => '34'],
            ['id' => '489','district' => 'RED HILL','ward_id' => '34'],
            ['id' => '490','district' => 'REFORM VILLAGE','ward_id' => '24'],
            ['id' => '491','district' => 'REGENTS PARK AND REGENTS POINT','ward_id' => '9'],
            ['id' => '492','district' => 'REST OF OFF-SHORE ISLANDS','ward_id' => '9'],
            ['id' => '493','district' => 'RICH PLAIN','ward_id' => '9'],
            ['id' => '494','district' => 'RIO CLARO','ward_id' => '6'],
            ['id' => '495','district' => 'RIVER ESTATE','ward_id' => '9'],
            ['id' => '496','district' => 'RIVERSDALE','ward_id' => '20'],
            ['id' => '497','district' => 'ROBERT HILL','ward_id' => '25'],
            ['id' => '498','district' => 'ROBERT VILLAGE','ward_id' => '19'],
            ['id' => '499','district' => 'ROCHARD ROAD','ward_id' => '25'],
            ['id' => '500','district' => 'ROMAIN LANDS','ward_id' => '27'],
            ['id' => '501','district' => 'ROUSILLAC','ward_id' => '12'],
            ['id' => '502','district' => 'ROXBOROUGH','ward_id' => '33'],
            ['id' => '503','district' => 'ROYSTONIA','ward_id' => '7'],
            ['id' => '504','district' => 'RUNNEMEDE','ward_id' => '28'],
            ['id' => '505','district' => 'SALAZAR VILLAGE','ward_id' => '12'],
            ['id' => '506','district' => 'SALIBYA VILLAGE','ward_id' => '14'],
            ['id' => '507','district' => 'SAM BOUCAUD','ward_id' => '27'],
            ['id' => '508','district' => 'SAMAROO VILLAGE','ward_id' => '1'],
            ['id' => '509','district' => 'SAN FRANCIQUE','ward_id' => '25'],
            ['id' => '510','district' => 'SAN JUAN','ward_id' => '27'],
            ['id' => '511','district' => 'SAN PEDRO(CHARUMA)','ward_id' => '5'],
            ['id' => '512','district' => 'SAN PEDRO(MANZANILLA)','ward_id' => '13'],
            ['id' => '513','district' => 'SAN RAPHAEL/BRAZIL','ward_id' => '23'],
            ['id' => '514','district' => 'SAN SOUCI','ward_id' => '36'],
            ['id' => '515','district' => 'SANGRE CHIQUITO','ward_id' => '13'],
            ['id' => '516','district' => 'SANGRE GRANDE','ward_id' => '13'],
            ['id' => '517','district' => 'SANTA CRUZ','ward_id' => '27'],
            ['id' => '518','district' => 'SANTA FLORA','ward_id' => '10'],
            ['id' => '519','district' => 'SANTA MAGARITA','ward_id' => '34'],
            ['id' => '520','district' => 'SANTA ROSA HEIGHTS','ward_id' => '1'],
            ['id' => '521','district' => 'SCARBOROUGH','ward_id' => '26'],
            ['id' => '522','district' => 'SCOTT ROAD VILLAGE','ward_id' => '25'],
            ['id' => '523','district' => 'SEALOTS','ward_id' => '21'],
            ['id' => '524','district' => 'SHERWOOD PARK','ward_id' => '1'],
            ['id' => '525','district' => 'SHORELANDS','ward_id' => '9'],
            ['id' => '526','district' => 'SIGNAL HILL/PATIENCE HILL(ST. DAVID)','ward_id' => '28'],
            ['id' => '527','district' => 'SIGNAL HILL/PATIENCE HILL(ST. PATRICK)','ward_id' => '32'],
            ['id' => '528','district' => 'SIPARIA','ward_id' => '25'],
            ['id' => '529','district' => 'SISTERS VILLAGE','ward_id' => '24'],
            ['id' => '530','district' => 'SIXTH COMPANY','ward_id' => '19'],
            ['id' => '531','district' => 'SOBO VILLAGE','ward_id' => '12'],
            ['id' => '532','district' => 'SOCONUSCO','ward_id' => '27'],
            ['id' => '533','district' => 'SOUTH OROPOUCHE','ward_id' => '25'],
            ['id' => '534','district' => 'SPEYSIDE','ward_id' => '30'],
            ['id' => '535','district' => 'SPRING GARDEN/SIGNAL HILL','ward_id' => '26'],
            ['id' => '536','district' => 'SPRING VILLAGE(MONTSERRAT)','ward_id' => '16'],
            ['id' => '537','district' => 'SPRING VILLAGE(TACARIGUA)','ward_id' => '34'],
            ['id' => '538','district' => 'SPRINGLAND/SAN FABIAN','ward_id' => '20'],
            ['id' => '539','district' => 'ST. ANDREW&#39;S VILLAGE','ward_id' => '7'],
            ['id' => '540','district' => 'ST. ANNS','ward_id' => '27'],
            ['id' => '541','district' => 'ST. AUGUSTINE','ward_id' => '34'],
            ['id' => '542','district' => 'ST. AUGUSTINE SOUTH','ward_id' => '34'],
            ['id' => '543','district' => 'ST. BARBS','ward_id' => '27'],
            ['id' => '544','district' => 'ST. CHARLES VILLAGE(CHAGUANAS)','ward_id' => '4'],
            ['id' => '545','district' => 'ST. CHARLES VILLAGE(NAPARIMA)','ward_id' => '18'],
            ['id' => '546','district' => 'ST. CLAIR','ward_id' => '21'],
            ['id' => '547','district' => 'ST. CROIX VILLAGE','ward_id' => '18'],
            ['id' => '548','district' => 'ST. HELENA VILLAGE','ward_id' => '8'],
            ['id' => '549','district' => 'ST. JAMES','ward_id' => '9'],
            ['id' => '550','district' => 'ST. JOHN','ward_id' => '25'],
            ['id' => '551','district' => 'ST. JOHN&#39;S VILLAGE(NAPARIMA)','ward_id' => '18'],
            ['id' => '552','district' => 'ST. JOHN&#39;S VILLAGE(SAN FERNANDO)','ward_id' => '22'],
            ['id' => '553','district' => 'ST. JOSEPH','ward_id' => '34'],
            ['id' => '554','district' => 'ST. JOSEPH VILLAGE','ward_id' => '22'],
            ['id' => '555','district' => 'ST. JULIEN','ward_id' => '24'],
            ['id' => '556','district' => 'ST. LUCIEN ROAD','ward_id' => '9'],
            ['id' => '557','district' => 'ST. MADELINE','ward_id' => '18'],
            ['id' => '558','district' => 'ST. MARGARET','ward_id' => '20'],
            ['id' => '559','district' => 'ST. MARY&#39;S VILLAGE','ward_id' => '17'],
            ['id' => '560','district' => 'ST. THOMAS VILLAGE','ward_id' => '4'],
            ['id' => '561','district' => 'STONE BRITE VILLAGE','ward_id' => '11'],
            ['id' => '562','district' => 'SUDAMA VILLAGE','ward_id' => '25'],
            ['id' => '563','district' => 'SUM SUM HILL(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '564','district' => 'SUM SUM HILL(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '565','district' => 'SURREY VILLAGE','ward_id' => '34'],
            ['id' => '566','district' => 'SYNE VILLAGE','ward_id' => '25'],
            ['id' => '567','district' => 'TABAQUITE(CHARUMA)','ward_id' => '5'],
            ['id' => '568','district' => 'TABAQUITE(MONTSERRAT)','ward_id' => '16'],
            ['id' => '569','district' => 'TABLELAND','ward_id' => '19'],
            ['id' => '570','district' => 'TACARIGUA','ward_id' => '34'],
            ['id' => '571','district' => 'TALPARO','ward_id' => '23'],
            ['id' => '572','district' => 'TAMANA','ward_id' => '35'],
            ['id' => '573','district' => 'TAMANA ROAD(ARIMA)','ward_id' => '1'],
            ['id' => '574','district' => 'TAMANA ROAD(SAN RAPHAEL)','ward_id' => '23'],
            ['id' => '575','district' => 'TAROUBA(NAPARIMA)','ward_id' => '18'],
            ['id' => '576','district' => 'TAROUBA(SAN FERNANDO)','ward_id' => '22'],
            ['id' => '577','district' => 'TECHIER VILLAGE','ward_id' => '12'],
            ['id' => '578','district' => 'THICK VILLAGE','ward_id' => '25'],
            ['id' => '579','district' => 'TOCO','ward_id' => '36'],
            ['id' => '580','district' => 'TODD&#39;S ROAD','ward_id' => '4'],
            ['id' => '581','district' => 'TODD&#39;S STATION','ward_id' => '8'],
            ['id' => '582','district' => 'TOMPIRE','ward_id' => '36'],
            ['id' => '583','district' => 'TORTUGA','ward_id' => '16'],
            ['id' => '584','district' => 'TRINCITY','ward_id' => '34'],
            ['id' => '585','district' => 'TRINTOC (POINTE A PIERRE)','ward_id' => '20'],
            ['id' => '586','district' => 'TULSA VILLAGE','ward_id' => '25'],
            ['id' => '587','district' => 'TUMPUNA ROAD','ward_id' => '1'],
            ['id' => '588','district' => 'TUNAPUNA','ward_id' => '34'],
            ['id' => '589','district' => 'TURURE(MANZANILLA)','ward_id' => '13'],
            ['id' => '590','district' => 'TURURE(TURURE)','ward_id' => '37'],
            ['id' => '591','district' => 'UNION PARK','ward_id' => '18'],
            ['id' => '592','district' => 'UNION VILLAGE(COCAL)','ward_id' => '6'],
            ['id' => '593','district' => 'UNION VILLAGE(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '594','district' => 'UPPER BELMONT','ward_id' => '27'],
            ['id' => '595','district' => 'UPPER ST. JAMES','ward_id' => '9'],
            ['id' => '596','district' => 'USINE ST. MADELINE','ward_id' => '18'],
            ['id' => '597','district' => 'VALENCIA(MANZANILLA)','ward_id' => '13'],
            ['id' => '598','district' => 'VALENCIA(VALENCIA)','ward_id' => '38'],
            ['id' => '599','district' => 'VALLEY VIEW','ward_id' => '34'],
            ['id' => '600','district' => 'VALSAYN','ward_id' => '34'],
            ['id' => '601','district' => 'VANCE RIVER','ward_id' => '12'],
            ['id' => '602','district' => 'VESSIGNY','ward_id' => '12'],
            ['id' => '603','district' => 'VICTORIA GARDENS','ward_id' => '9'],
            ['id' => '604','district' => 'VICTORIA VILLAGE(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '605','district' => 'VICTORIA VILLAGE(SAN FERNANDO)','ward_id' => '22'],
            ['id' => '606','district' => 'VICTORIA VILLAGE(SAVANNA GRANDE)','ward_id' => '24'],
            ['id' => '607','district' => 'VISTABELLA','ward_id' => '18'],
            ['id' => '608','district' => 'WADDLE VILLAGE','ward_id' => '10'],
            ['id' => '609','district' => 'WALLERFIELD','ward_id' => '1'],
            ['id' => '610','district' => 'WARREN VILLAGE(COUVA)','ward_id' => '7'],
            ['id' => '611','district' => 'WARREN VILLAGE(CUNUPIA)','ward_id' => '8'],
            ['id' => '612','district' => 'WATER HOLE','ward_id' => '9'],
            ['id' => '613','district' => 'WATERLOO(CHAGUANAS)','ward_id' => '4'],
            ['id' => '614','district' => 'WATERLOO(COUVA)','ward_id' => '7'],
            ['id' => '615','district' => 'WATERLOO(ORTOIRE)','ward_id' => '19'],
            ['id' => '616','district' => 'WATERLOO(POINTE-A-PIERRE)','ward_id' => '20'],
            ['id' => '617','district' => 'WELCOME','ward_id' => '4'],
            ['id' => '618','district' => 'WELLINGTON','ward_id' => '18'],
            ['id' => '619','district' => 'WEST MOORINGS','ward_id' => '9'],
            ['id' => '620','district' => 'WHIM','ward_id' => '28'],
            ['id' => '621','district' => 'WHITE LAND','ward_id' => '20'],
            ['id' => '622','district' => 'WILLAMSVILLE','ward_id' => '24'],
            ['id' => '623','district' => 'WINDSOR PARK','ward_id' => '7'],
            ['id' => '624','district' => 'WOODBROOK','ward_id' => '21'],
            ['id' => '625','district' => 'WOODLAND(NAPARIMA)','ward_id' => '18'],
            ['id' => '626','district' => 'WOODLAND(SIPARIA)','ward_id' => '25'],
        ]);
    }
}
